// src/components/Counter.svelte
<script>
let count = 0;

function add() {
    count += 1;
}

function subtract() {
    count -= 1;
}
</script>

<div class="container">
    <h1>Svelte Counter</h1>
    <div class="counter">
        <button on:click={subtract}>-</button>
        <pre>{count}</pre>
        <button on:click={add}>+</button>
    </div>
</div>

// src/components/Counter.tsx
import { useState } from "react";

export default function Counter() {
    const [count, setCount] = useState(0);
    const add = () => setCount((i) => i + 1);
    const subtract = () => setCount((i) => i - 1);

    return (
        <div className="container">
            <h1>React counter</h1>
            <div className="counter">
                <button onClick={subtract}>-</button>
                <pre>{count}</pre>
                <button onClick={add}>+</button>
            </div>
        </div>
    );
}
